GET  https://movies-app-2021-node.herokuapp.com/movies
###

POST  https://movies-app-2021-node.herokuapp.com/movies
Content-Type: application/json

{
    "title":"JameBon 008",
    "years":"2010",
    "rate":"MA"

}
###